# Generated by Django 5.2.6 on 2025-10-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('millwork_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='saturday_hours',
            field=models.CharField(default='9:00 AM - 4:00 PM', help_text='Saturday hours', max_length=100),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='saturday_hours_arabic',
            field=models.CharField(blank=True, help_text='Saturday hours in Arabic', max_length=100),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='sunday_hours',
            field=models.CharField(default='Closed', help_text="Sunday hours (e.g., 'Closed' or time)", max_length=100),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='sunday_hours_arabic',
            field=models.CharField(default='مغلق', help_text='Sunday hours in Arabic', max_length=100),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='weekday_hours',
            field=models.CharField(default='8:00 AM - 6:00 PM', help_text='Monday to Friday hours', max_length=100),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='weekday_hours_arabic',
            field=models.CharField(blank=True, help_text='Monday to Friday hours in Arabic', max_length=100),
        ),
    ]
