# Generated by Django 5.2.6 on 2025-10-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('millwork_site', '0002_companyinfo_saturday_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_arabic', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('description_arabic', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, help_text='Certification logo or badge', null=True, upload_to='certifications/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_in_business', models.PositiveIntegerField(default=8, help_text='Years in business')),
                ('projects_completed', models.PositiveIntegerField(default=500, help_text='Total projects completed')),
                ('happy_clients', models.PositiveIntegerField(default=350, help_text='Number of satisfied clients')),
                ('team_members', models.PositiveIntegerField(default=15, help_text='Number of team members')),
                ('years_label', models.CharField(default='Years of Excellence', max_length=100)),
                ('years_label_arabic', models.CharField(default='سنوات من التميز', max_length=100)),
                ('projects_label', models.CharField(default='Projects Completed', max_length=100)),
                ('projects_label_arabic', models.CharField(default='مشاريع مكتملة', max_length=100)),
                ('clients_label', models.CharField(default='Happy Clients', max_length=100)),
                ('clients_label_arabic', models.CharField(default='عملاء سعداء', max_length=100)),
                ('team_label', models.CharField(default='Expert Team', max_length=100)),
                ('team_label_arabic', models.CharField(default='فريق خبراء', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Statistics',
                'verbose_name_plural': 'Company Statistics',
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_arabic', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('description_arabic', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class or SVG identifier', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Why Choose Us Item',
                'verbose_name_plural': 'Why Choose Us Items',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='service_areas',
            field=models.TextField(blank=True, help_text='Comma-separated list of areas served (e.g., Doha, Lusail, West Bay)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='service_areas_arabic',
            field=models.TextField(blank=True, help_text='Comma-separated list of areas in Arabic'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='showroom_address',
            field=models.CharField(blank=True, help_text='Physical showroom/office address', max_length=500),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='showroom_address_arabic',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
