# Generated by Django 5.2.6 on 2025-10-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('millwork_site', '0004_alter_project_image_projectimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Question (keyword-rich)', max_length=300)),
                ('question_arabic', models.CharField(blank=True, max_length=300)),
                ('answer', models.TextField(help_text='Detailed answer with keywords')),
                ('answer_arabic', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('general', 'General'), ('products', 'Products'), ('installation', 'Installation'), ('pricing', 'Pricing'), ('warranty', 'Warranty')], default='general', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
