# Generated by Django 5.2.6 on 2025-10-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('millwork_site', '0005_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('aluminium_kitchen', 'Aluminium Kitchen Cabinet Luxurious Design'), ('upvc_door_window', 'UPVC Door & Window'), ('glass_door_partition', 'Glass Door & Partition'), ('aluminum_door_window', 'Aluminum Door & Window')], max_length=50),
        ),
    ]
